# config.yaml
data:
  symbols: ["BTCUSDT", "ETHUSDT", "DOGEUSDT", "TRXUSDT", "BNBUSDT",
            "XRPUSDT", "ADAUSDT", "LINKUSDT", "XLMUSDT", "BCHUSDT",
            "HBARUSDT", "LTCUSDT", "ZECUSDT"]   # 支持多币种
  # SOLUSDT 2020年8月才发行
  # AVAXUSDT 2020年9月才发行
  # SHIBUSDT 2021年5月才发行
  # DOTUSDT 2020年8月才发行
  # TAOUSDT 2024年4月才发行
  #symbols: ["BTCUSDT"]
  intervals: ["1d", "1m"]           # 支持多周期
  #intervals: ["1d"]
  start_date: "2020-01"
  end_date: "2025-09"

paths:
  raw_dir: "data/raw/binance/spot"
  processed_dir: "data/processed/csv"
  datasets_dir: "data/datasets"
  logs_dir: "logs"

split:
  train_end: "2023-12-31"
  val_end: "2024-12-31"