# config.yaml
data:
  symbols: ["BTCUSDT", "ETHUSDT"]   # 支持多币种
  #symbols: ["BTCUSDT"]
  #intervals: ["1d", "1m"]           # 支持多周期
  intervals: ["1d"]
  start_date: "2020-01"
  end_date: "2025-09"

paths:
  raw_dir: "data/raw/binance/spot"
  processed_dir: "data/processed/csv"
  datasets_dir: "data/datasets"
  logs_dir: "logs"

split:
  train_end: "2023-12-31"
  val_end: "2024-12-31"