# config.yaml
data:
  symbols: ["BTCUSDT", "ETHUSDT"]   # 支持多币种
  intervals: ["1d", "1m"]           # 支持多周期
  start_date: "2020-01"
  end_date: "2025-10"

paths:
  raw_dir: "data/raw/binance/spot"
  processed_dir: "data/processed/csv"
  datasets_dir: "data/datasets"
  logs_dir: "logs"

split:
  train_end: "2024-01-01"
  val_end: "2025-01-01"